#!/usr/bin/env python3

import argparse
import boto3
import time


def start_instance(instance_id, interval):
    ec2 = boto3.client("ec2")

    while True:
        try:
            response = ec2.start_instances(InstanceIds=[instance_id])
            print("Start request sent. Response:", response)
            break  # Exit the loop if the start request was successful
        except Exception as e:
            print("Error starting instance:", e)
            time.sleep(interval)  # Wait for specified interval before trying again


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Start an EC2 instance with retries.")
    parser.add_argument(
        "instance_id", type=str, help="The ID of the EC2 instance to start."
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=30,
        help="Interval between retries in seconds (default: 30 seconds).",
    )

    args = parser.parse_args()

    start_instance(args.instance_id, args.interval)
